# Generated by Django 6.0.1 on 2026-01-17 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0002_alter_pecaos_valor_unitario_imagemcomentarioos'),
    ]

    operations = [
        migrations.AddField(
            model_name='pecaos',
            name='imagem',
            field=models.ImageField(default=None, upload_to='os/pecas/'),
            preserve_default=False,
        ),
    ]
