# Generated by Django 6.0.1 on 2026-01-17 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0003_pecaos_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pecaos',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='os/pecas/'),
        ),
    ]
