# Generated by Django 6.0.1 on 2026-01-17 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquina',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='maquinas/'),
        ),
    ]
